book_store/book/urls.py
from django.urls import path
from .views import ListBooks, ListBorrowedBooks, GetBookDetails, GetUserBooks, BorrowBook, ReturnBook, AddBook, EditBook, DeleteBook

app_name = "book"

urlpatterns = [
    path("", ListBooks, name="list_books"),
    path("borrowed/", ListBorrowedBooks, name="list_borrowed_books"),
    path('<int:pk>/', GetBookDetails, name="details"),
    path("me/", GetUserBooks, name="my_books"),
    path("borrow/<int:pk>/", BorrowBook, name="borrow"),
    path("return/<int:pk>/", ReturnBook, name="return"),
    path("add/", AddBook, name="add"),
    path("edit/<int:pk>/", EditBook, name="edit"),
    path("delete/<int:pk>/", DeleteBook, name="delete"),
]

book_store/book_store/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home

app_name = "book_store"

urlpatterns = [
    path("home/", Home),
    path('admin/', admin.site.urls),
    path("api/", include([
        path("user/", include("user.urls")),
        path("auth/", include("authentication.urls")),
        path("book/", include("book.urls"))
    ])),
]

book_store/book/models.py
from django.db import models
from user.models import BUser


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    state = models.CharField(max_length=10, choices=[(
        "Available", "Available"), ("Taken", "Taken")], default="Available")
    return_date = models.DateField()
    price = models.FloatField()
    borrowing_user = models.ForeignKey(
        BUser, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

book_store/book/forms.py
from django.forms import ModelForm
from .models import Book


class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = "__all__"

book_store/book/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from authentication.views import attach_user_context, is_admin, is_logged_in, is_student

from user.models import BUser
from .models import Book
from .forms import BookForm


def ListBooks(request):

    if not is_logged_in(request):
        return redirect("/api/auth/login")
    books_set = Book.objects.all()
    context = {
        "books": books_set
    }
    return render(request, "book/list.html", attach_user_context(request, context))


def ListBorrowedBooks(request):

    if not is_logged_in(request):
        return redirect("/api/auth/login")

    if not is_admin(request):
        return redirect("/api/auth/login")

    books_set = Book.objects.filter(state="Taken")
    context = {
        "books": books_set
    }
    return render(request, "book/list.html", attach_user_context(request, context))


def GetBookDetails(request, pk=1):

    if not is_logged_in(request):
        return redirect("/api/auth/login")

    book_data = Book.objects.get(pk=pk)
    context = {
        "id": book_data.id,
        "title": book_data.title,
        "author": book_data.author,
        "state": book_data.state,
        "return_date": book_data.return_date,
        "price": book_data.price,
        "borrowing_user": book_data.borrowing_user,
    }
    return render(request, "book/details.html", attach_user_context(request, context))


def GetUserBooks(request):
    if not is_logged_in(request):
        return redirect("/api/auth/login")

    if not is_student(request):
        return redirect("/api/auth/login")

    user_id = request.session["id"]
    user = BUser.objects.get(id=user_id)
    context = {
        "books": user.book_set.all(),
        "can_return": True
    }
    return render(request, "book/list.html", attach_user_context(request, context))


@csrf_exempt
def BorrowBook(request, pk):
    if not is_logged_in(request):
        return redirect("/api/auth/login")

    if not is_student(request):
        return redirect("/api/auth/login")

    user_id = request.session["id"]

    selected_book = Book.objects.get(pk=pk)
    selected_book.state = "Taken"
    selected_book.save()
    selected_user = BUser.objects.get(id=user_id)
    selected_user.book_set.add(selected_book)
    selected_user.save()

    return redirect("/api/book/")


@csrf_exempt
def ReturnBook(request, pk):
    if not is_logged_in(request):
        return redirect("/api/auth/login")

    if not is_student(request):
        return redirect("/api/auth/login")

    user_id = request.session["id"]
    selected_book = Book.objects.get(pk=pk)
    selected_book.state = "Available"
    selected_book.save()
    selected_user = BUser.objects.get(id=user_id)
    selected_user.book_set.remove(selected_book)
    selected_user.save()
    selected_book = Book.objects.get(pk=pk)

    return redirect("/api/book/")


def AddBook(request):

    if not is_logged_in(request):
        return redirect("/api/auth/login")

    if not is_admin(request):
        return redirect("/api/auth/login")

    if request.method == "GET":
        bookForm = BookForm()
        context = {
            "form": bookForm,
            "button_text": "Add Book"
        }
        return render(request, "book/add.html", attach_user_context(request, context))
    elif request.method == "POST":
        bookForm = BookForm(request.POST)
        if (bookForm.is_valid()):
            bookForm.save()
            return redirect("/api/book/")
        else:
            context = {
                "form": bookForm,
                "button_text": "Add Book"
            }
            return render(request, "book/add.html", attach_user_context(request, context))


def EditBook(request, pk):
    if not is_logged_in(request):
        return redirect("/api/auth/login")

    if not is_admin(request):
        return redirect("/api/auth/login")

    book_obj = Book.objects.get(pk=pk)
    if request.method == "GET":
        bookForm = BookForm(instance=book_obj)
        context = {
            "form": bookForm,
            "button_text": "Edit Book"
        }
        return render(request, "book/add.html", attach_user_context(request, context))
    elif request.method == "POST":
        bookForm = BookForm(request.POST, instance=book_obj)
        if (bookForm.is_valid()):
            bookForm.save()
            return redirect("/api/book/")
        else:
            context = {
                "form": bookForm,
                "button_text": "Edit Book"
            }
            return render(request, "book/add.html", attach_user_context(request, context))


def DeleteBook(request, pk):
    if not is_logged_in(request):
        return redirect("/api/auth/login")

    if not is_admin(request):
        return redirect("/api/auth/login")

    Book.objects.get(pk=pk).delete()
    return redirect("/api/book")

book_store/book/templates/book/add.html
{% extends "book_store/base.html" %} 

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'book/add.css' %}" />
<div class="form-content">
  <h3>{{ button_text }}</h3>
  <form method="post">
    {% csrf_token %} 
    {{ form.as_div }}
    <button type="submit">{{ button_text }}</button>
  </form>
</div>

{% endblock %}

book_store/book/templates/book/details.html
{% extends "book_store/base.html" %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'book/details.css' %}" />

<div class="book-content">
  <h2 class="book-title">{{title}}</h2>
  <p class="book-field"><span>author: </span>{{author}}</p>
  <p class="book-field"><span>state: </span>{{state}}</p>
  <p class="book-field"><span>return date: </span>{{return_date}}</p>
  <p class="book-field"><span>price: </span>{{price}}</p>
  {% if borrowing_user %}
  <p class="book-field"><span>Borrowing User: </span>{{borrowing_user}}</p>
  {% endif %}

  <div class="controls">
    <form method="get" action="{% url 'book:edit' id %}">
      <button class="edit-btn" type="submit">Edit</button>
    </form>
    <form method="post" action="{% url 'book:delete' id %}">
      {% csrf_token %}
      <button class="delete-btn" type="submit">Delete</button>
    </form>
  </div>
</div>

{% endblock %}

book_store/book/templates/book/list.html
{% extends "book_store/base.html" %} {% load static %} {% block content %}

<link rel="stylesheet" href="{% static 'book/list.css' %}" />
<ul class="books-list">
  {% for book in books %}

  <li>
    <a href="{% url 'book:details' book.id %}">{{book.title}}</a>
    <p class="author"><span>author:</span> {{book.author}}</p>
    {%if book.state == "Available" %}
    <p class="available">{{ book.state}}</p>
    {% elif not can_return %}
    <p class="taken">{{ book.state}}</p>
    {% endif %}
    {% if not is_admin and book.state != "Taken" %}
    <form method="post" action="{% url 'book:borrow' book.id %}">
      <button type="submit">Borrow</button>
    </form>
    {% endif %}
    {% if can_return %}
    <form method="post" action="{% url 'book:return' book.id %}">
      <button class="return-btn" type="submit">Return</button>
    </form>
    {% endif %}
  </li>

  {% endfor %}
</ul>

{% endblock %}

book_store/book/templates/book/list_borrowed.html
{% extends "book_store/base.html" %}

{% block content %}

<ul>
  {% for book in books %}
  
    <li>
      <a href="{% url 'book:details' book.id %}">{{book.title}}</a>
      <p>{{book.author}}</p>
      <p>{{book.state}}</p>
    </li>

  {% endfor %}


</ul>

{% endblock %}