book_store/authentication/urls.py
from django.urls import path
from .views import Login, Logout, Signup, ChangePassword

app_name = "authentication"

urlpatterns = [
    path("signup/", Signup, name="signup"),
    path("login/", Login, name="login"),
    path("logout/", Logout, name="logout"),
    path("change_password/", ChangePassword, name="change_password"),
]

book_store/book/urls.py
from django.urls import path
from .views import ListBooks, ListBorrowedBooks, GetBookDetails, GetUserBooks, BorrowBook, ReturnBook, AddBook, EditBook, DeleteBook

app_name = "book"

urlpatterns = [
    path("", ListBooks, name="list_books"),
    path("borrowed/", ListBorrowedBooks, name="list_borrowed_books"),
    path('<int:pk>/', GetBookDetails, name="details"),
    path("me/", GetUserBooks, name="my_books"),
    path("borrow/<int:pk>/", BorrowBook, name="borrow"),
    path("return/<int:pk>/", ReturnBook, name="return"),
    path("add/", AddBook, name="add"),
    path("edit/<int:pk>/", EditBook, name="edit"),
    path("delete/<int:pk>/", DeleteBook, name="delete"),
]

book_store/book_store/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home

app_name = "book_store"

urlpatterns = [
    path("home/", Home),
    path('admin/', admin.site.urls),
    path("api/", include([
        path("user/", include("user.urls")),
        path("auth/", include("authentication.urls")),
        path("book/", include("book.urls"))
    ])),
]

book_store/user/urls.py
from django.urls import path
from .views import ListUsers,  GetUser

app_name = "user"

urlpatterns = [
    path("", ListUsers, name="list_users"),
    path("get/", GetUser, name="get_user"),

]

book_store/book_store/views.py
from django.shortcuts import render

from authentication.views import attach_user_context


def Home(request):

    return render(request, "book_store/base.html", attach_user_context(request, {}))

book_store/book_store/templates/book_store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'book_store/style.css'%}" />
    <title>Book Store</title>
  </head>
  <body>
    <nav>
      <div>
        <img src="{% static 'book_store/logo.png' %}" />
        <h2>Book Store</h2>
      </div>
      <ul>
        {% if logged_in %} {% if is_admin %}
        <li>
          <a href="{% url 'user:list_users' %}">All Users</a>
        </li>
        <li>
          <a href="{% url 'book:list_books' %}">All Books</a>
        </li>
        <li>
          <a href="{% url 'book:list_borrowed_books' %}">All Borrowed Books</a>
        </li>
        <li>
          <a href="{% url 'book:add' %}">Add Book</a>
        </li>
        <li>
          <a href="{% url 'user:get_user' %}">Get User</a>
        </li>
        <li>
          <a href="{% url 'authentication:change_password' %}"
            >Change Password</a
          >
        </li>
        {% else %}
        <li>
          <a href="{% url 'book:list_books' %}">All Books</a>
        </li>
        <li>
          <a href="{% url 'book:my_books' %}">My Books</a>
        </li>
        <li>
          <a href="#">Profile</a>
        </li>
        {% endif %}
        <li>
          <a href="{% url 'authentication:logout' %}">Logout</a>
        </li>

        {% else %}
        <li>
          <a href="{% url 'authentication:login' %}">Login</a>
        </li>
        <li>
          <a href="{% url 'authentication:signup' %}">Signup</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>